CREATE DATABASE IF NOT EXISTS shop;
GRANT ALL PRIVILEGES ON shop.* TO 'root'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON shop.* TO 'root'@'localhost' IDENTIFIED BY '123456';
FLUSH PRIVILEGES
USE shop
